# Site settings
title: Academic Research Network @ UM
email: aresearchnetwork@umich.edu
description: > # this means to ignore newlines until "baseurl:"
  Academic Research Network
  A Network for all incoming freshman with prior experience in research.
baseurl: ""
url: https://arn-um.github.io

# Build settings
markdown: kramdown
exclude: [README.md]
keep_files: [images assets]
